# Linux e distribuição Ubuntu
os: linux
dist: focal

# Linguagens Utilizadas para Desenvolver a Aplicação
language: python

# Versão que a aplicação suporta.
python:
  "3.8"

 # Instalação de Módulos que são necessários para a Aplicação
 install:
 pip install flask pytest